# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Assertion do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_key,
    :expectation
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.TupleKey.t,
    :expectation => boolean()
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Assertion do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_key, :struct, OpenFGA.Model.TupleKey, options)
  end
end

