# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.AuthorizationModel do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :schema_version,
    :type_definitions
  ]

  @type t :: %__MODULE__{
    :id => String.t | nil,
    :schema_version => String.t | nil,
    :type_definitions => [OpenFGA.Model.TypeDefinition.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.AuthorizationModel do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type_definitions, :list, OpenFGA.Model.TypeDefinition, options)
  end
end

