# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Difference do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :base,
    :subtract
  ]

  @type t :: %__MODULE__{
    :base => OpenFGA.Model.Userset.t,
    :subtract => OpenFGA.Model.Userset.t
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Difference do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:base, :struct, OpenFGA.Model.Userset, options)
    |> deserialize(:subtract, :struct, OpenFGA.Model.Userset, options)
  end
end

