# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ExpandResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tree
  ]

  @type t :: %__MODULE__{
    :tree => OpenFGA.Model.UsersetTree.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ExpandResponse do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tree, :struct, OpenFGA.Model.UsersetTree, options)
  end
end

