# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ListObjectsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :object_ids
  ]

  @type t :: %__MODULE__{
    :object_ids => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ListObjectsResponse do
  def decode(value, _options) do
    value
  end
end

