# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Nodes do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :nodes
  ]

  @type t :: %__MODULE__{
    :nodes => [OpenFGA.Model.Node.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Nodes do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:nodes, :list, OpenFGA.Model.Node, options)
  end
end

