# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ReadRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_key,
    :authorization_model_id,
    :page_size,
    :continuation_token
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.TupleKey.t,
    :authorization_model_id => String.t | nil,
    :page_size => integer() | nil,
    :continuation_token => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ReadRequest do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_key, :struct, OpenFGA.Model.TupleKey, options)
  end
end

