# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.ReadAuthorizationModelResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :authorization_model
  ]

  @type t :: %__MODULE__{
    :authorization_model => OpenFGA.Model.AuthorizationModel.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.ReadAuthorizationModelResponse do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:authorization_model, :struct, OpenFGA.Model.AuthorizationModel, options)
  end
end

