# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Status do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :message,
    :details
  ]

  @type t :: %__MODULE__{
    :code => integer() | nil,
    :message => String.t | nil,
    :details => [OpenFGA.Model.Any.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Status do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:details, :list, OpenFGA.Model.Any, options)
  end
end

