# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleChange do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_key,
    :operation,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :tuple_key => OpenFGA.Model.TupleKey.t | nil,
    :operation => OpenFGA.Model.TupleOperation.t | nil,
    :timestamp => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.TupleChange do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_key, :struct, OpenFGA.Model.TupleKey, options)
    |> deserialize(:operation, :struct, OpenFGA.Model.TupleOperation, options)
  end
end

