# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.Tuple do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :key,
    :timestamp
  ]

  @type t :: %__MODULE__{
    :key => OpenFGA.Model.TupleKey.t | nil,
    :timestamp => DateTime.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.Tuple do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:key, :struct, OpenFGA.Model.TupleKey, options)
  end
end

