# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleToUserset do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tupleset,
    :computedUserset
  ]

  @type t :: %__MODULE__{
    :tupleset => OpenFGA.Model.ObjectRelation.t | nil,
    :computedUserset => OpenFGA.Model.ObjectRelation.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.TupleToUserset do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tupleset, :struct, OpenFGA.Model.ObjectRelation, options)
    |> deserialize(:computedUserset, :struct, OpenFGA.Model.ObjectRelation, options)
  end
end

