# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TupleKeys do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tuple_keys
  ]

  @type t :: %__MODULE__{
    :tuple_keys => [OpenFGA.Model.TupleKey.t]
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.TupleKeys do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tuple_keys, :list, OpenFGA.Model.TupleKey, options)
  end
end

