# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.TypeDefinition do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :relations,
    :metadata
  ]

  @type t :: %__MODULE__{
    :type => String.t,
    :relations => %{optional(String.t) => OpenFGA.Model.Userset.t} | nil,
    :metadata => OpenFGA.Model.Metadata.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.TypeDefinition do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:relations, :map, OpenFGA.Model.Userset, options)
    |> deserialize(:metadata, :struct, OpenFGA.Model.Metadata, options)
  end
end

