# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.UsersetTreeDifference do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :base,
    :subtract
  ]

  @type t :: %__MODULE__{
    :base => OpenFGA.Model.Node.t | nil,
    :subtract => OpenFGA.Model.Node.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.UsersetTreeDifference do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:base, :struct, OpenFGA.Model.Node, options)
    |> deserialize(:subtract, :struct, OpenFGA.Model.Node, options)
  end
end

