# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.UsersetTree do
  @moduledoc """
  A UsersetTree contains the result of an Expansion.
  """

  @derive [Poison.Encoder]
  defstruct [
    :root
  ]

  @type t :: %__MODULE__{
    :root => OpenFGA.Model.Node.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.UsersetTree do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:root, :struct, OpenFGA.Model.Node, options)
  end
end

