# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.WriteRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :writes,
    :deletes,
    :authorization_model_id
  ]

  @type t :: %__MODULE__{
    :writes => OpenFGA.Model.TupleKeys.t | nil,
    :deletes => OpenFGA.Model.TupleKeys.t | nil,
    :authorization_model_id => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.WriteRequest do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:writes, :struct, OpenFGA.Model.TupleKeys, options)
    |> deserialize(:deletes, :struct, OpenFGA.Model.TupleKeys, options)
  end
end

