# NOTE: This file is auto generated by OpenAPI Generator 6.1.0-SNAPSHOT (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule OpenFGA.Model.WriteAuthorizationModelRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :type_definitions,
    :schema_version
  ]

  @type t :: %__MODULE__{
    :type_definitions => [OpenFGA.Model.TypeDefinition.t],
    :schema_version => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenFGA.Model.WriteAuthorizationModelRequest do
  import OpenFGA.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type_definitions, :list, OpenFGA.Model.TypeDefinition, options)
  end
end

